# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

    gradle(

    properties: {
      'versionCode' => ENV['ANDROID_VERSIONCODE'],
      'versionName' => ENV['ANDROID_VERSIONNAME'],
      'applicationName' => ENV['ANDROID_APPLICATIONAME']
      # ...
    },

    task: "clean assembleDebug"
    )

    notify = true
    notes = "Merkinsio Upload"
    build_path = "../build/outputs/apk/#{ENV['ANDROID_APPLICATIONAME']}_#{ENV['ANDROID_VERSIONNAME']}-debug.apk"

    tags = "merkinsio"

    command = "curl \"http://dashboard.sandbox.applivery.com/api/builds\""
        command += " -H \"Authorization: #{ENV['APPLIVERY_APIKEY']}\""
        command += " -F app=\"#{ENV['APPLIVERY_APPID']}\""
        command += " -F versionName=\"#{ENV['ANDROID_VERSIONNAME']}\""
        command += " -F notes=\"#{notes}\""
        command += " -F notify=#{notify}"
        command += " -F os=android"
        command += " -F tags=\"#{tags}\""
        command += " -F package=@\"#{build_path}\""

        Actions.sh(command)


  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    #slack(
    # message: "Successfully Merkinsio deployed new App Update to Crashlytics"
    #)
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
